### ISSUE TITLE
Text in "Most Viewed Shows" gets cut off

### ISSUE THREAD

**Issue by techeverri** [michaldrabik/showly-2.0#80]
Hey there 👋
_Thanks for this awesome app!_ 🚀 

### Device

- Galaxy S10
- Android 10
- Default font size

### Steps to reduce

- Open the app
- Press "My Shows" tab
- Press circle icons (Statistics) next to the settings gear icon
- Scroll all the way down to the "Most Viewed Shows" section

### Screenshots

| Most Viewed Shows | Font size |
|---|---|
| ![Screenshot_20201017-000354_Showly 20](https://user-images.githubusercontent.com/3720424/96319904-35523300-1011-11eb-9146-1533d3de0ff5.jpg) | ![Screenshot_20201017-005034_Settings](https://user-images.githubusercontent.com/3720424/96320484-caa1f700-1012-11eb-8ed9-60521cad36a4.jpg) |

**Comment by techeverri** [comment]
I'd like to give it a try to fix it 🤠

_Apart from following the steps from the README, Do you know which part of the code would be a good place to start?_

**Comment by michaldrabik** [comment]
Hi, thanks for reporting.
Seems like not that hard layout bug.

It's this view and its layout:
https://github.com/michaldrabik/Showly-2.0/blob/master/ui-statistics/src/main/java/com/michaldrabik/ui_statistics/views/mostWatched/StatisticsMostWatchedItemView.kt

**Comment by techeverri** [comment]
What version of Java do I need to be able to run/build the project? @michaldrabik 

I have a fairly recent version (`jdk-13.0.2.jdk` specifically) of the JDK installed on my laptop (macOS)

I'm getting the following error when trying to accept the license for the Android SDK

```bash
~/Library/Android/sdk/tools/bin
❯ ./sdkmanager --licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more
```

**Comment by techeverri** [comment]
I tried but couldn't find a way to fix it.

To reproduce the issue on any smartphone simply got to the settings and increase the font size. Most of the text in other parts of the app becomes bigger without getting cut off but the numbers in the "most watched" list are affected.

I will unassign myself from but the ticket will stay open 👍

**Comment by michaldrabik** [comment]
It's OK. Thanks. I'll try to take care of it.

**Comment by michaldrabik** [comment]
Manged to fixed an issue. Small layout modification was needed:
https://github.com/michaldrabik/showly-2.0/commit/b83923003c07d49861446361d344717c72928a15
